apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myreadings-dev

namePrefix: ""

resources:
  - ../../base

patches:
  - path: patches/resource-limits-app.yaml
  - path: patches/resource-limits-ui.yaml
