apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myreadings-dev

namePrefix: ""

resources:
  - ../../base

patches:
  - path: patches/resource-limits-app.yaml
  - path: patches/resource-limits-ui.yaml
  - path: patches/monolith-oidc-issuer.yaml

images:
- name: quay.io/too-common-name/myreadings-app
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-app
  newTag: 9c62d8d7e2e9be123bf294b6fa3764f5eedb4d9a
- name: quay.io/too-common-name/myreadings-ui
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-ui
  newTag: c032a91b17aa8bb8a2b4018fd852d90b59743500
