apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreadings-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: myreadings-app
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreadings-ui
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: myreadings-ui
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
