apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreadings-user-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: myreadings-user-service
    app.kubernetes.io/part-of: myreadings
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myreadings-user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myreadings-user-service
        app.kubernetes.io/part-of: myreadings
    spec:
      containers:
        - name: myreadings-user-service
          image: quay.io/too-common-name/myreadings-user-service:latest
          ports:
            - containerPort: 8083
              protocol: TCP
          envFrom:
            - configMapRef:
                name: myreadings-user-service-config
          env:
            - name: POSTGRES_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: myreadings-db-pguser-myreadings-user
                  key: host
            - name: POSTGRES_PORT_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: myreadings-db-pguser-myreadings-user
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: myreadings-db-pguser-myreadings-user
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myreadings-db-pguser-myreadings-user
                  key: password
            - name: KEYCLOAK_HOSTNAME
              value: myreadings-keycloak-service
            - name: KC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myreadings-keycloak-initial-admin
                  key: password
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: myreadings-rabbitmq-default-user
                  key: host
            - name: RABBITMQ_PORT_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: myreadings-rabbitmq-default-user
                  key: port
            - name: RABBITMQ_APP_USER
              valueFrom:
                secretKeyRef:
                  name: myreadings-rabbitmq-default-user
                  key: username
            - name: RABBITMQ_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myreadings-rabbitmq-default-user
                  key: password
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
