apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - task-maven-test.yaml
  - task-maven-test-dind.yaml
  - task-acs-image-scan.yaml
  - pipeline-maven.yaml
  - pipeline-node.yaml
  # Triggers
  - triggers/rbac.yaml
  - triggers/trigger-binding.yaml
  - triggers/tt-app.yaml
  - triggers/tt-user-service.yaml
  - triggers/tt-ui.yaml
  - triggers/event-listener.yaml
  - triggers/route.yaml
