apiVersion: batch/v1
kind: Job
metadata:
  name: configure-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: myreadings
    app.kubernetes.io/component: config
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: ansible-configurator
      restartPolicy: Never
      containers:
        - name: ansible
          image: quay.io/rh-ee-drossi/myreadings-ee:latest
          command:
            - ansible-playbook
            - configure-keycloak.yml
            - -e
            - "app_namespace=myreadings-dev"
            - -e
            - "keycloak_realm_name=my-readings"
            - -e
            - "keycloak_client=myreadings-client"
            - -e
            - "keycloak_client_display_name=My Readings Application"
            - -e
            - "keycloak_allow_registration=true"
            - -e
            - "frontend_url=https://myreadings-ui-myreadings-dev.apps.cluster-nvhnt.dynamic.redhatworkshops.io"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
