apiVersion: v1
kind: ServiceAccount
metadata:
  name: myreadings-trigger
  labels:
    app.kubernetes.io/part-of: myreadings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myreadings-trigger
  labels:
    app.kubernetes.io/part-of: myreadings
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myreadings-trigger
  labels:
    app.kubernetes.io/part-of: myreadings
subjects:
  - kind: ServiceAccount
    name: myreadings-trigger
roleRef:
  kind: Role
  name: myreadings-trigger
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myreadings-trigger-interceptors
  labels:
    app.kubernetes.io/part-of: myreadings
subjects:
  - kind: ServiceAccount
    name: myreadings-trigger
    namespace: myreadings-dev
roleRef:
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
  apiGroup: rbac.authorization.k8s.io
