apiVersion: v1
kind: ConfigMap
metadata:
  name: myreadings-user-service-config
data:
  QUARKUS_OIDC_TOKEN_ISSUER: "https://myreadings-keycloak-myreadings-dev.apps.cluster-nvhnt.dynamic.redhatworkshops.io/realms/my-readings"
