apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: myreadings-configure-keycloak
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  name: myreadings-configure-keycloak
  connection_secret: aap-connection
  organization: Default
  project: myreadings-gitops
  playbook: ansible/configure-keycloak.yml
  inventory: Demo Inventory
  execution_environment: myreadings-ee
  extra_vars:
    app_namespace: myreadings-dev
    keycloak_realm_name: my-readings
    keycloak_client: myreadings-client
    keycloak_client_display_name: "My Readings Application"
    keycloak_allow_registration: true
    frontend_url: https://myreadings-ui-myreadings-dev.apps.cluster-nvhnt.dynamic.redhatworkshops.io
