apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-reader-rbac.yaml
  - project.yaml
  - job-template-keycloak.yaml
  - job-template-rabbitmq.yaml
  - job-run-keycloak.yaml
  - job-run-rabbitmq.yaml
