apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleProject
metadata:
  name: myreadings-gitops
  namespace: ansible-automation-platform
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  name: myreadings-gitops
  connection_secret: aap-connection
  organization: Default
  scm_type: git
  repo: https://github.com/too-common-name/myreadings-gitops.git
  branch: main
