apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: myreadings-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  image: quay.io/rh-ee-drossi/myreadings-keycloak:latest
  instances: 1
  hostname:
    strict: false
  http:
    httpEnabled: true
  db:
    vendor: postgres
    host: myreadings-db-primary
    port: 5432
    database: keycloak_db
    usernameSecret:
      name: myreadings-db-pguser-keycloak-user
      key: user
    passwordSecret:
      name: myreadings-db-pguser-keycloak-user
      key: password
  proxy:
    headers: xforwarded
  unsupported:
    podTemplate:
      spec:
        containers:
          - resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
