apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: myreadings-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  to:
    kind: Service
    name: myreadings-keycloak-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
